language: java
sudo: false
install: true

services:
  - mongodb

addons:
  sonarcloud:
    organization: "hhbravo-github"
    token:
      secure: $SONAR_TOKEN # encrypted value of your token

jdk:
  - oraclejdk8

#before_install:
  # - mysql -e 'CREATE DATABASE IF NOT EXISTS lead CHARACTER SET utf8 COLLATE utf8_general_ci;'
  # - mysql -u travis lead < database/lead_schema.sql

before_script:
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

script:
 - "./mvn clean install"

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.sonarscanner'